from typing import Any, Mapping

from botocore.exceptions import ClientError as ClientError
from botocore.model import ServiceModel
from botocore.utils import get_service_module_name as get_service_module_name

class BaseClientExceptions:
    ClientError: Any = ...
    def __init__(self, code_to_exception: Mapping[str, ClientError]) -> None: ...
    def from_code(self, error_code: str) -> ClientError: ...
    def __getattr__(self, name: str) -> None: ...

class ClientExceptionsFactory:
    def __init__(self) -> None: ...
    def create_client_exceptions(self, service_model: ServiceModel) -> BaseClientExceptions: ...
