repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        language: system
        pass_filenames: false
        entry: uvx ruff check --fix
      - id: format
        name: format
        language: system
        pass_filenames: false
        entry: uvx ruff format
      - id: vulture
        name: vulture
        language: system
        pass_filenames: false
        entry: uvx vulture
      - id: pyright
        name: pyright
        language: system
        pass_filenames: false
        entry: uv run pyright mypy_boto3_builder
      - id: mypy
        name: mypy
        language: system
        pass_filenames: false
        entry: uv run mypy mypy_boto3_builder
      - id: pytest
        name: pytest
        language: system
        pass_filenames: false
        entry: uv run pytest
