from typing import Any, Iterable, List, Mapping, Optional

def get_resource_ignore_params(params: Mapping[str, Any]) -> List[str]: ...
def is_resource_action(action_handle: Any) -> bool: ...
def get_resource_public_actions(resource_class: Any) -> List[Any]: ...
def get_identifier_values_for_example(identifier_names: Iterable[str]) -> str: ...
def get_identifier_args_for_signature(identifier_names: Iterable[str]) -> str: ...
def get_identifier_description(resource_name: str, identifier_name: str) -> str: ...
def add_resource_type_overview(
    section: Any, resource_type: str, description: str, intro_link: Optional[str] = ...
) -> None: ...
