from .eventstream import AioEventStream as AioEventStream
from botocore.parsers import EC2QueryParser, JSONParser, QueryParser, ResponseParserFactory, RestJSONParser, RestXMLParser
from typing import Any

class AioRestXMLParser(RestXMLParser): ...
class AioEC2QueryParser(EC2QueryParser): ...
class AioQueryParser(QueryParser): ...

class AioJSONParser(JSONParser):
    async def parse(self, response, shape): ...

class AioRestJSONParser(RestJSONParser): ...

PROTOCOL_PARSERS: Any

class AioResponseParserFactory(ResponseParserFactory):
    def create_parser(self, protocol_name): ...

def create_parser(protocol): ...
