import logging
from collections.abc import Generator
from io import BytesIO

from _typeshed import Incomplete
from s3transfer.constants import GB as GB
from s3transfer.constants import MB as MB
from s3transfer.exceptions import TransferNotDoneError as TransferNotDoneError
from s3transfer.futures import BaseTransferFuture as BaseTransferFuture
from s3transfer.futures import BaseTransferMeta as BaseTransferMeta
from s3transfer.utils import CallArgs as CallArgs
from s3transfer.utils import OSUtils as OSUtils
from s3transfer.utils import get_callbacks as get_callbacks

logger: logging.Logger

class CRTCredentialProviderAdapter:
    def __init__(self, botocore_credential_provider) -> None: ...
    def __call__(self): ...

def create_s3_crt_client(
    region,
    botocore_credential_provider: Incomplete | None = ...,
    num_threads: Incomplete | None = ...,
    target_throughput=...,
    part_size=...,
    use_ssl: bool = ...,
    verify: Incomplete | None = ...,
): ...

class CRTTransferManager:
    def __init__(
        self, crt_s3_client, crt_request_serializer, osutil: Incomplete | None = ...
    ) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type, exc_value, *args) -> None: ...
    def download(
        self,
        bucket,
        key,
        fileobj,
        extra_args: Incomplete | None = ...,
        subscribers: Incomplete | None = ...,
    ): ...
    def upload(
        self,
        fileobj,
        bucket,
        key,
        extra_args: Incomplete | None = ...,
        subscribers: Incomplete | None = ...,
    ): ...
    def delete(
        self, bucket, key, extra_args: Incomplete | None = ..., subscribers: Incomplete | None = ...
    ): ...
    def shutdown(self, cancel: bool = ...) -> None: ...

class CRTTransferMeta(BaseTransferMeta):
    def __init__(
        self, transfer_id: Incomplete | None = ..., call_args: Incomplete | None = ...
    ) -> None: ...
    @property
    def call_args(self): ...
    @property
    def transfer_id(self): ...
    @property
    def user_context(self): ...

class CRTTransferFuture(BaseTransferFuture):
    def __init__(
        self, meta: Incomplete | None = ..., coordinator: Incomplete | None = ...
    ) -> None: ...
    @property
    def meta(self): ...
    def done(self): ...
    def result(self, timeout: Incomplete | None = ...) -> None: ...
    def cancel(self) -> None: ...
    def set_exception(self, exception) -> None: ...

class BaseCRTRequestSerializer:
    def serialize_http_request(self, transfer_type, future) -> None: ...

class BotocoreCRTRequestSerializer(BaseCRTRequestSerializer):
    def __init__(self, session, client_kwargs: Incomplete | None = ...) -> None: ...
    def serialize_http_request(self, transfer_type, future): ...

class FakeRawResponse(BytesIO):
    def stream(
        self, amt: int = ..., decode_content: Incomplete | None = ...
    ) -> Generator[Incomplete, None, None]: ...

class CRTTransferCoordinator:
    transfer_id: Incomplete
    def __init__(
        self, transfer_id: Incomplete | None = ..., s3_request: Incomplete | None = ...
    ) -> None: ...
    @property
    def s3_request(self): ...
    def set_done_callbacks_complete(self) -> None: ...
    def wait_until_on_done_callbacks_complete(self, timeout: Incomplete | None = ...) -> None: ...
    def set_exception(self, exception, override: bool = ...) -> None: ...
    def cancel(self) -> None: ...
    def result(self, timeout: Incomplete | None = ...) -> None: ...
    def done(self): ...
    def set_s3_request(self, s3_request) -> None: ...

class S3ClientArgsCreator:
    def __init__(self, crt_request_serializer, os_utils) -> None: ...
    def get_make_request_args(
        self, request_type, call_args, coordinator, future, on_done_after_calls
    ): ...
    def get_crt_callback(
        self,
        future,
        callback_type,
        before_subscribers: Incomplete | None = ...,
        after_subscribers: Incomplete | None = ...,
    ): ...

class RenameTempFileHandler:
    def __init__(self, coordinator, final_filename, temp_filename, osutil) -> None: ...
    def __call__(self, **kwargs) -> None: ...

class AfterDoneHandler:
    def __init__(self, coordinator) -> None: ...
    def __call__(self, **kwargs) -> None: ...
