from typing import Any, List
from botocore.docs.service import ServiceDocumenter as BaseServiceDocumenter

class ServiceDocumenter(BaseServiceDocumenter):
    EXAMPLE_PATH: str
    sections: List[str]
    def __init__(self, service_name: str, session: Any, root_docs_path: str) -> None: ...
    def document_service(self) -> bytes: ...
    def client_api(self, section: Any) -> None: ...
    def resource_section(self, section: Any) -> None: ...
